### ISSUE TITLE
[Legacy DB] Drop Site log tables (more in desc)

### ISSUE THREAD

**Issue by Tooseriuz** [rfcx/arbimon-db#12]
Drop these table, not being used anymore
- `site_log_files`
- `site_event_log`
- `site_data_log_tech_types`
- `site_data_log_plug_types`
- `site_data_log_health_types`
- `site_data_log`
- `site_connection_types`
- `site_connection_log`
- `site_aggrs`

**Comment by rassokhina-e** [comment]
Approved!
