### ISSUE TITLE
[Legacy DB] update uri for models table

### ISSUE THREAD

**Issue by rassokhina-e** [rfcx/arbimon-db#20]
old uri `project_3/models/job_151_7_1.mod`

add 3 new columns to support uri combining
* uri_param1 (tinyint) - 151
* uri_param2 (tinyint) - 7
* uri_param3 (tinyint) - 1

* remove old uri column
* update `arbimon-jobs` repo to support this logic

**Comment by Tooseriuz** [comment]
the size of the table is 0.64 MB. it is not worth cleansing at the moment.
