### ISSUE TITLE
[Legacy DB] Drop `mic`, `recorder` and `version` columns in `recordings` table

### ISSUE THREAD

**Issue by Tooseriuz** [rfcx/arbimon-db#38]

**Comment by rassokhina-e** [comment]
Ant:
>I don’t think we can just delete the 3 columns because some users might want this data. I was thinking to move the data into the meta column, but now i suspect that it won’t make much difference to reducing the table size.
[4:48](https://rfcx.slack.com/archives/C02G4AR2GEL/p1728305295393779?thread_ts=1728287911.056559&cid=C02G4AR2GEL)
So perhaps we have to leave those 3 columns for now.
